---
title: "First Knit"
author: "Your Name"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended high school in Cameroon in Douala and the school was  (IUC INSTITUT UNIVERTAIRE DE LA COTE), yes i graduated. Maths is easier than English. i was very good in anatomy AND PHYSIOLOGY. they are science subjects, and i love science.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer 
I am using a window computer. on a scale of 1 to 10, i will say 5 because i am not too dumb and I am neither an expert.
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  my first name Desmond is the name i prefer my classmates should me with , including instructors. The name i prefer is Desy. 
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
 I want to be a Rn IN 5 years. Biology. a Bachelor degree.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  yes, i have been to southafrica. No I have never been to military.
  The Navy is the military branch i would love to get in, because i love water.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  No, i have never done maths 115 or 116. I didn't know about the fact that maths 115 satisfies several transfer institutions. I always go for an A grade in every subject i take, and my plann is to get an A grade in maths 115,to have good transcript results and to be the best.
   
 






  




